# Generated by Django 5.0.4 on 2025-01-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_userassignment_user_email_userassignment_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassignment',
            old_name='user_uuid',
            new_name='user_oid',
        ),
    ]
