# Generated by Django 5.0.4 on 2025-01-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_rename_user_uuid_userassignment_user_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='user_role',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
