# Generated by Django 5.0.4 on 2025-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_news_oid_project_oid_team_oid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='team_oid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
